"""empty message

Revision ID: 5633f72e2d5a
Revises: 95cf85f5420a
Create Date: 2023-03-09 12:14:49.077559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5633f72e2d5a'
down_revision = '95cf85f5420a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poketeam', schema=None) as batch_op:
        batch_op.drop_constraint('poketeam_team_id_fkey', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poketeam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('poketeam_team_id_fkey', 'poketeam', ['team_id'], ['id'])

    # ### end Alembic commands ###
