"""empty message

Revision ID: d8143eace0f3
Revises: 7bfaa1fdb308
Create Date: 2023-03-09 13:03:37.014619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8143eace0f3'
down_revision = '7bfaa1fdb308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poketeam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_caught_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('poketeam_caught_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'caught', ['team_caught_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['team_user_id'], ['id'])
        batch_op.drop_column('caught_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poketeam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caught_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('poketeam_caught_id_fkey', 'caught', ['caught_id'], ['id'])
        batch_op.drop_column('team_user_id')
        batch_op.drop_column('team_caught_id')

    # ### end Alembic commands ###
