"""empty message

Revision ID: d9211a95fcb9
Revises: 0254e34667c5
Create Date: 2023-03-02 18:36:01.769018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9211a95fcb9'
down_revision = '0254e34667c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('lastname')
        batch_op.drop_column('fistname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fistname', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
